/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zjl_example_com_ndktest_Java2CJNI */

#ifndef _Included_zjl_example_com_ndktest_Java2CJNI
#define _Included_zjl_example_com_ndktest_Java2CJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zjl_example_com_ndktest_Java2CJNI
 * Method:    java2C
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zjl_example_com_ndktest_Java2CJNI_java2C
  (JNIEnv *env, jobject instance){
  return env -> NewStringUTF("Hello i am from JNI!");
  }

#ifdef __cplusplus
}
#endif
#endif


